# Generated by Django 4.2.3 on 2023-08-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='tarih'),
        ),
    ]
